### ISSUE TITLE
Endgame book for opposite-colored bishops

### ISSUE THREAD

**Issue by SFisGOD** [official-stockfish/books#14]
@snicolet  Is it easy to generate an endgame book containing OCB? I can probably filter the endgame book and choose only FENs with each side having one bishop but obviously it does not guarantee an OCB.

I want to tune a separate output layer for OCB and I need an OCB book for that. Thanks!

**Comment by Dboingue** [comment]
I would be curious about such endgame books.  Where can I find those on the web.   and what is OCB? sorry only have partial knowledge, but it is evolving, with every Q and A I can get, or read from others.  Many other filters could be used.
Or extract position databases from the book nodes.  thanks in  advance.  First time I read about such books.
