### ISSUE TITLE
The noob_4moves.pgn.zip has a weird path

### ISSUE THREAD

**Issue by JustLinuxUser** [official-stockfish/books#42]
The file mentioned in the title, has this path, when unzipping
`Users/stephane/Programmation/GitHub/books-copie/noob_4moves.pgn`
![image](https://github.com/official-stockfish/books/assets/75628709/edda4918-19a1-4d5b-9eb0-155e296c3cce)

**Comment by Disservin** [comment]
The following books have this
```
Found 'Users/' in Drawkiller_balanced_big.pgn.zip
Found 'Users/' in noob_2moves.pgn.zip
Found 'Users/' in noob_3moves.pgn.zip
Found 'Users/' in noob_4moves.pgn.zip
```

I'll push a fix so that all zips have the same structure
